GreenG|/home/oracl3/Pictures/wallpapers/greenw.jpg
Anime Brochacho|/home/oracl3/Pictures/wallpapers/anuw.jpg
Abstract|/home/oracl3/Pictures/wallpapers/abstract.png
Devochki :3|/home/oracl3/Pictures/wallpapers/wallhaven-8geml1.jpg
Neo Arch |/home/oracl3/Pictures/wallpapers/neoarch.png